### ISSUE TITLE
fps really low 

### ISSUE THREAD

**Issue by maylad31** [madhawav/YOLO3-4-Py#53]
Hi i installed gpu version following the instructions but I get very slow fps.It seems my gpu is not being used.Please help.

**Comment by pherris** [comment]
I agree - I'm using the docker setup and tried both:

```
ENV GPU 1
ENV OPENCV 1
## Download and compile YOLO3-4-Py ##
WORKDIR /
RUN git clone https://github.com/madhawav/YOLO3-4-Py.git
WORKDIR /YOLO3-4-Py
RUN pip3 install pkgconfig
RUN pip3 install cython
RUN python3 setup.py build_ext --inplace
```
and
```
WORKDIR /
WORKDIR /YOLO3-4-Py
RUN pip3 install pkgconfig
RUN pip3 install cython
RUN pip3 install yolo34py-gpu

## Run test ##
```
but the performance is very slow...  could it be my hardware is not setup correctly?

**Comment by maylad31** [comment]
hi could you please give me more details about fps in your local environment.

**Comment by pherris** [comment]
For me it’s more like spf (about 6) - running on a Mac.

**Comment by maylad31** [comment]
thanks sorry for the late reply you may close this issue yes i solved the problem i had cuda installed and path and everything was set but still it wasn't working so i updated my nvidia driver reinstalled cuda and it worked thanks i would like to ask why the darknet fps is more than python wrapper i understand it would be slow in python but with darknet i get 18 fps and with python wrapper it drops to around 11-12 fps

**Comment by madhawav** [comment]
Hi @maylad31,
There is a drop in fps caused by conversion of python images (numpy arrays) to darknet images. The drop depends on the resolution of images.
